{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "redis-ha.fullname" . }}-network-policy
{{- if .Values.networkPolicy.annotations }}
  annotations:
{{ toYaml .Values.networkPolicy.annotations | indent 4}}
{{- end }}
  labels:
{{ include "labels.standard" . | indent 4 }}
  {{- if .Values.networkPolicy.labels }}
{{ toYaml .Values.networkPolicy.labels | indent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ template "redis-ha.name" . }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
      - podSelector: 
          matchLabels:
            release: {{ .Release.Name }}
            app: {{ template "redis-ha.name" . }}
      ports:
        - port: {{ .Values.redis.port }}
          protocol: TCP
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
{{-  range $rule := .Values.networkPolicy.egressRules }}
    - to:
{{ toYaml $rule.selectors | indent 9 }}
      ports:
{{- if $rule.ports }}
{{ toYaml $rule.ports | indent 9 }}  
{{- else }}
        - port: {{ .Values.redis.port }}
          protocol: TCP
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
{{- end }}
{{- end }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            release: {{ .Release.Name }}
            app: {{ template "redis-ha.name" . }}
      ports: 
        - port: {{ .Values.redis.port }}
          protocol: TCP
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
{{-  range $rule := .Values.networkPolicy.ingressRules }}
    - from:
{{ toYaml $rule.selectors | indent 7 }}
      ports:
{{- if $rule.ports }}
{{ toYaml $rule.ports | indent 9 }}
{{- else }}
        - port: {{ .Values.redis.port }}
          protocol: TCP
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
{{- end }}
{{- end }}
{{- end }}

